title: "Your Awesome Title"
name: "Buhara"
email: metinzorlu@msn.com 
description: Kişisel blog sayfası

plugins:
  - jekyll-seo-tag
  - jekyll-feed

# jekyll-feed settings
feed:
  # Site başlığı
  title: "Your Awesome Title"
  # Sitenizin kısa açıklaması
  description: "Kişisel blog sayfası"
  # Feed dosyasının adı (isteğe bağlı)
  name: "feed.xml"

baseurl: "/buhara" 
url: "" 
twitter_username: deruni
github_username: mtnzorlu 
youtube_username: deruni79

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# navmenu 
atitle: About
aurl: /about
btitle: Works
burl: /works
ctitle: Quote
curl: /quote
