title: "Your Awesome Title"
name: "Buhara"
email: metinzorlu@msn.com 
description: "Kişisel blog sayfası"
info: "Bu Site Hakkında"
quotes: "Güzel Sözler"


baseurl: "/buhara" 
url: "" 
twitter_username: deruni
github_username: mtnzorlu 
youtube_username: deruni79

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  
paginate: 3

paginate_path: "/blog/page:num/"

feed:
  title: "Your Awesome Title"
  description: "Kişisel blog sayfası"
  name: "feed.xml"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# navmenu 
mtitle: Home
atitle: About
aurl: /about
btitle: Works
burl: /works
ctitle: Blog
curl: /blog
