title: "Buhara"
name: "Buhara"
email: metinzorlu@msn.com 
description: Kişisel blog sayfası

baseurl: "" 
url: "" 
twitter_username: deruni
github_username: mtnzorlu


plugins:
  - jekyll-feed
  - jekyll-seo-tag