title: "Buhara"
name: "Buhara"
email: metinzorlu@msn.com 
description: "Kişisel blog sayfası"
info: "About This Site"
quotes: "Nice Words"
buttonTitle: "Other Posts"
nPosts: "New Posts"


baseurl: "https://mtnzorlu.github.io/buhara" 
url: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  
paginate: 3

paginate_path: "/blog/page:num/"

feed:
  title: "Your Awesome Title"
  description: "Kişisel blog sayfası"
  name: "feed.xml"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# navmenu 
mtitle: Home
atitle: About
aurl: /about
btitle: Works
burl: /works
ctitle: Blog
curl: /blog
